import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SWANKY',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
        <header>
          <p>header here</p>
        </header>
        <main className='flex-grow'>
          {children}
        </main>
        <footer>
          <p>footer here</p>
        </footer>
      </body>
    </html>
  )
}
